[package]
name = "piquelctl"
version = "0.1.0"
edition = "2024"
default-run = "piquelctl"

[dependencies]
piquel-core = { path = "../piquel-core/" }
clap = { version = "4", features = ["derive"] }
tokio.workspace = true
